/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author Joaqu
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mniEntrenadores = new javax.swing.JMenu();
        mniEntrenadorAgregar = new javax.swing.JMenuItem();
        mniEntrenadorEditar = new javax.swing.JMenuItem();
        mniEntrenadorListar = new javax.swing.JMenuItem();
        mniEntrenadorEliminar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniPokemonAgregar = new javax.swing.JMenuItem();
        mniPokemonEditar = new javax.swing.JMenuItem();
        mniPokemonListar = new javax.swing.JMenuItem();
        mniPokemonEliminar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(680, 384));

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        mniEntrenadores.setText("Entrenadores");

        mniEntrenadorAgregar.setText("Agregar");
        mniEntrenadorAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEntrenadorAgregarActionPerformed(evt);
            }
        });
        mniEntrenadores.add(mniEntrenadorAgregar);

        mniEntrenadorEditar.setText("Editar");
        mniEntrenadorEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEntrenadorEditarActionPerformed(evt);
            }
        });
        mniEntrenadores.add(mniEntrenadorEditar);

        mniEntrenadorListar.setText("Listar");
        mniEntrenadorListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEntrenadorListarActionPerformed(evt);
            }
        });
        mniEntrenadores.add(mniEntrenadorListar);

        mniEntrenadorEliminar.setText("Eliminar");
        mniEntrenadorEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEntrenadorEliminarActionPerformed(evt);
            }
        });
        mniEntrenadores.add(mniEntrenadorEliminar);

        jMenuBar1.add(mniEntrenadores);

        jMenu2.setText("Pokemones");

        mniPokemonAgregar.setText("Agregar");
        mniPokemonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPokemonAgregarActionPerformed(evt);
            }
        });
        jMenu2.add(mniPokemonAgregar);

        mniPokemonEditar.setText("Editar");
        mniPokemonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPokemonEditarActionPerformed(evt);
            }
        });
        jMenu2.add(mniPokemonEditar);

        mniPokemonListar.setText("Listar");
        mniPokemonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPokemonListarActionPerformed(evt);
            }
        });
        jMenu2.add(mniPokemonListar);

        mniPokemonEliminar.setText("Eliminar");
        mniPokemonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPokemonEliminarActionPerformed(evt);
            }
        });
        jMenu2.add(mniPokemonEliminar);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("COMBATE");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniEntrenadorListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEntrenadorListarActionPerformed
        // TODO add your handling code here:
        ListaDeEntrenadores l = new ListaDeEntrenadores();
        l.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_mniEntrenadorListarActionPerformed

    private void mniPokemonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPokemonListarActionPerformed
        // TODO add your handling code here:
        ListarPokemones l = new ListarPokemones();
       
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniPokemonListarActionPerformed

    private void mniPokemonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPokemonEditarActionPerformed
        // TODO add your handling code here:
        EditarPokemones e = new EditarPokemones();
       
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniPokemonEditarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void mniEntrenadorEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEntrenadorEditarActionPerformed
        // TODO add your handling code here:
        EditarEntrenadores e = new EditarEntrenadores();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniEntrenadorEditarActionPerformed

    private void mniEntrenadorAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEntrenadorAgregarActionPerformed
        // TODO add your handling code here:
        AgregarEntrenadores a = new AgregarEntrenadores();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniEntrenadorAgregarActionPerformed

    private void mniEntrenadorEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEntrenadorEliminarActionPerformed
        // TODO add your handling code here:
        EliminarEntrenadores l = new EliminarEntrenadores();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniEntrenadorEliminarActionPerformed

    private void mniPokemonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPokemonAgregarActionPerformed
        // TODO add your handling code here:
        AgregarPokemones l = new AgregarPokemones();
       
        l.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_mniPokemonAgregarActionPerformed

    private void mniPokemonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPokemonEliminarActionPerformed
        // TODO add your handling code here:
        EliminarPokemones l = new EliminarPokemones();
       
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniPokemonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem mniEntrenadorAgregar;
    private javax.swing.JMenuItem mniEntrenadorEditar;
    private javax.swing.JMenuItem mniEntrenadorEliminar;
    private javax.swing.JMenuItem mniEntrenadorListar;
    private javax.swing.JMenu mniEntrenadores;
    private javax.swing.JMenuItem mniPokemonAgregar;
    private javax.swing.JMenuItem mniPokemonEditar;
    private javax.swing.JMenuItem mniPokemonEliminar;
    private javax.swing.JMenuItem mniPokemonListar;
    // End of variables declaration//GEN-END:variables
}
